# Este archivo cloudbuild.yaml define cómo se ejecuta el proceso de construcción de tu imagen Docker
# y su despliegue en Google Cloud Run. Asegúrate de que este archivo esté en la raíz de tu repositorio de GitHub.

steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/absolute-text-478800-r0/audiosplitter'  # Usa el nombre de tu GCR para la imagen Docker
      - '.'  # Directorio donde se encuentra tu Dockerfile (ajústalo si es necesario)

  # Paso 2: Desplegar la imagen a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        gcloud run deploy audiosplitter \
          --image gcr.io/absolute-text-478800-r0/audiosplitter \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated  # Permite que la aplicación sea pública (ajusta si es necesario)

# Opciones de configuración de la compilación
options:
  logging: CLOUD_LOGGING_ONLY  # Usar Cloud Logging para los logs de la compilación
  # Para usar un bucket de logs personalizado, puedes descomentar la siguiente línea y reemplazar '<bucket_name>'
  # build:
  #   logs_bucket: gs://example_audiospliter_v1  # Aquí es donde se almacenarán los logs de la compilación

# Especifica la cuenta de servicio para la compilación (opcional)
# Si no necesitas usar una cuenta de servicio personalizada, puedes eliminar esta sección.
serviceAccount: projects/absolute-text-478800-r0/serviceAccounts/<service_account_email>

# Especifica las imágenes generadas (en este caso, tu imagen Docker)
images:
  - 'gcr.io/absolute-text-478800-r0/audiosplitter'

# Aquí puedes agregar más configuraciones si es necesario para tu compilación
